Pull request for finishing mobile version
Miliyonayalew/Portfolio pull request #2
Opened 2022-08-19 22:43 UTC by Miliyonayalew

Added the work section to the project
Added the about my self section to the project
Added the contact form section to the project
Added styles by using flexbox and grid
finished the mobile version part of the portfolio

2022-08-19 23:39 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Miliyonayalew 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 23:39 UTC, tresorsawasawa commented on index.html
> +            </div> -->
- [ ] Kindly make sure you remove all the commented code lines in your code base to make it cleaner and professional.

2022-08-19 23:39 UTC, tresorsawasawa commented on styles.css
> +
- [ ] As required for the project kindly make sure the main container of the projects has a `display:grid` i.e you should use `grid` instead of `flexbox`  to display the project's cards.

2022-08-19 23:39 UTC, tresorsawasawa commented on styles.css
> +}
@- [ ] Kindly make sure your project cards stick to the ones from the Figma design to match the project's requirements. You can see that your design is different from the Figma template, especially the `height` of `background color block` and `text`, spacing between card content, the padding on the `See Project` button, `font size` on technologies text on each category(e.g: Ruby on rails, CSS, Rspec,...),...

| Figma Design | Figma Design |
| ------------------- | --------------------- | 
| ![project_card_f3](https://user-images.githubusercontent.com/83042742/185718044-fbd1638e-d756-42d1-87d6-d3203925087c.png) | ![Screenshot from 2022-08-20 01-12-43](https://user-images.githubusercontent.com/83042742/185718231-045f550b-a172-420c-b78d-6bb4ea9dc72a.png) |

2022-08-19 23:39 UTC, tresorsawasawa commented on styles.css
> +}
- [ ] Kindly make sure the **About  me** section follows the design like the one on the Figma template(**e.g.: Add the full background image and position it perfectly, missing the `Get My Resume` button as it overlapped by technologies cards,...**). Make sure you check everything from the Figma template and apply it to your project.

| Figma Design | Your Design | 
| ------------------ | ------------------- |
| ![about_f3](https://user-images.githubusercontent.com/83042742/185718953-ca12e4cb-9869-47c9-9084-1a47fbf58432.png) | ![Screenshot from 2022-08-20 01-27-45](https://user-images.githubusercontent.com/83042742/185719076-06a036db-4d23-4e6c-8b2e-0ab27e25a52d.png) |

2022-08-19 23:39 UTC, tresorsawasawa commented on styles.css
> +}
- [ ] Kindly make sure your **technologies cards** follow the design like the ones from the Figma template. Right now they overlap the **Get My Resume** button from the **About Me section**, there is no spacing between them,...
You check all details from Figma to match your design to your chosen template.

| Figma Design | Your Design |
| ------------------ | ----------------- |
| ![techology_cards](https://user-images.githubusercontent.com/83042742/185719614-30ae2623-d40b-41a2-8bd2-0eb4631f7f9c.png) | ![Screenshot from 2022-08-20 01-32-20](https://user-images.githubusercontent.com/83042742/185719627-b71d1abb-d11c-47ce-ac53-af1408b97b2c.png) |

2022-08-20 08:46 UTC, emmiiorji approved these changes
Hi @Miliyonayalew , 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![brilliant-well-done](https://user-images.githubusercontent.com/20554583/185736813-2054fdbc-ffaf-45cc-b5ec-f87dcc8bda8e.gif)


## Highlights

- Descriptive pull request
- Good commit messages
- Required changes have been implemented properly

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 08:56 UTC, merged