pull request for contact form and finish the mobile version
Miliyonayalew/Portfolio pull request #3
Opened 2022-08-23 21:20 UTC by Miliyonayalew

Added a contact form to the project
Added an action and method attribute to the form
Added ul, li, input field to the form
Added HTML5 validations as per the requirement
Collected data by using the Formspree service
Added styles to contact form using flexbox
Implemented button interaction

2022-08-23 21:41 UTC, Kamba56 requested changes
Hi @Miliyonayalew, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![AlmostThereGIF](https://user-images.githubusercontent.com/94551484/186271518-e1ec073c-ed88-40ea-949d-5a9ff08cf0b2.gif)

## Highlights
- [ ] All linters checks passed
- [ ] Descriptive PR title and description

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [Optional] It's better to follow commit message standards by making them capitalized and in the imperative form (Example: 'Modify readme file' instead of 'modified readme'). This way, your commit history will be more readable and more professional ✨

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 21:41 UTC, Kamba56 commented on index.html
>              </form>
- [ ] Please you should stick to the design as much as possible. Kindly make your colors match the design and also add the background image
*Your design*
![Screenshot 2022-08-23 223110](https://user-images.githubusercontent.com/94551484/186270611-a743ca0f-67b9-41e6-b5d4-c159722faf80.png)

*Figma template*
![Screenshot 2022-08-23 223237](https://user-images.githubusercontent.com/94551484/186270616-ae99064b-3183-4324-a474-3846030a8a2f.png)


- [ ] Please make sure the hover and pressed state on your buttons matches that of the design template.
![Screenshot 2022-08-20 203951](https://user-images.githubusercontent.com/94551484/186270872-ac368b09-777c-4fa6-b551-38ace2e2c700.png)
-

2022-08-23 21:41 UTC, Kamba56 commented on index.html
>              </div>
- [Optional] Consider using an unordered list to list out your social icons. This is best practice for HTML semantics.😁

2022-08-24 01:21 UTC, levy002 approved these changes
### Hi @Miliyonayalew , 
### I'm Levy, your PR reviewer

Excellent for implementing the requested changes. :sunglasses: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

## Status: APPROVED 🔥 🔥 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 13:23 UTC, merged